# Step 1: Build your app using Maven and Java 17
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copy everything and build the WAR
COPY . .
RUN mvn clean package -DskipTests

# Step 2: Run the built WAR in Tomcat
FROM tomcat:9.0-jdk17
WORKDIR /usr/local/tomcat

# Remove default Tomcat apps
RUN rm -rf webapps/*

# Copy the WAR generated by Maven
COPY --from=build /app/target/*.war webapps/ROOT.war

# Expose port 8080 for Railway
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
